### ISSUE TITLE
Disable session creation on certain routes

### ISSUE THREAD

**Issue by Xstoudi** [adonisjs/session#58]
... or at least allow to trigger session creation manually.

## Why this feature is required (specific use-cases will be appreciated)?
I don't want to create a session for every visitors of my website and I don't want to create a session on every routes either.

## Have you tried any other work arounds?
I read the doc and didn't see a satisfying workaround.

## Are you willing to work on it with little guidance?
Yes.

**Comment by thetutlage** [comment]
Not sure how this can work pratically. Sessions id is sent to the browser inside cookies. Imagine this example:

- Request comes in to `/foo` and server sends the cookies in response including the session id.
- Next request comes in to `/bar` and you have disabled sessions for this request. So this time the cookies in the response is does not contain the session id. The browser removes the old cookies and also the session id.
- Now the new request to `/foo` will not have the session id and hence there is no session.

**Comment by Xstoudi** [comment]
Got it.

**Comment by bnason** [comment]
Sorry to resurrect this issue but I don't believe going to a route that doesn't set the session cookie will actually remove it.

To verify this, I setup 2 routes. One created a new cookie and the second one just returns the value of the cookie.

My use case is for my health check endpoints with Kubernetes. Each time it accesses the health check endpoint a new session gets created and saved.

```
Route.get('/cookieSet', async ({ response }) => {
	response.cookie('foo', 'bar')
	return {}
})

Route.get('/cookieGet', async ({ request }) => {
	const value = request.cookie('foo')
	return { 'cookie': value }
})
```

```
> curl --cookie /tmp/cookie.txt --cookie-jar /tmp/cookie.txt \
http://localhost:3333/cookieSet -v
{}

> cat /tmp/cookie.txt
#HttpOnly_localhost	FALSE	/	FALSE	1608758729	foo	eyJtZXNzYWdlIjoiYmFyIn0

> curl --cookie /tmp/cookie.txt --cookie-jar /tmp/cookie.txt \
http://localhost:3333/cookieGet
{"cookie":"bar"}
```

**Comment by RomainLanz** [comment]
Hey @bnason! 👋 

We have [an RFC ](https://github.com/adonisjs/rfcs/pulls) to discuss about this feature/
