### ISSUE TITLE
a new session file for each new request from mobile app

### ISSUE THREAD

**Issue by ElyesaErgezenPXL** [adonisjs/session#75]
Hi there,

I'm using AdonisJs version 4.1 but I faced with a problem when making requests from mobile app to my api.
When making request it will create a new session file for each new request.

Example:
Fetching categories in the home screen of app will create a new session file. When clicking on category it will fetch the products for that category and this request will create also a new session file.

Is there a way to create only one session file for making the request from mobile app?

Any help will be appreciated.
Best regards.

**Comment by thetutlage** [comment]
Since mobile apps do not persist cookies, it is expected outcome. I don't think you should be relying on the sessions when creating mobile apps

**Comment by ElyesaErgezenPXL** [comment]
Is it possible to exclude the url where I fetch data for mobile app? Because I use the web version of AdonisJS v4.1. My web app and mobile app uses this api.

**Comment by ElyesaErgezenPXL** [comment]
I found out that even making requests from web app for example navigating to other page or reloading page creates a new session file on every request.

**Comment by thetutlage** [comment]
@ElyesaErgezenPXL Can you reproduce this behavior in a fresh application and share its repo with me?

**Comment by intoxopox** [comment]
@ElyesaErgezenPXL Did you ever solve this?

**Comment by RomainLanz** [comment]
> @ElyesaErgezenPXL Did you ever solve this?

If you have the same issue, please create a new issue with a reproduction on a fresh installation.
