### ISSUE TITLE
Property `session` does not exist on type `HttpContextContract`

### ISSUE THREAD

**Issue by svicalifornia** [adonisjs/session#77]
## Package version

```
    "@adonisjs/core": "^5.8.0",
    "@adonisjs/repl": "^3.1.0",
    "@adonisjs/session": "^6.4.0",
```

## Node.js and npm version

v16.14.2

## Sample Code (to reproduce the issue)

Following the session docs here: https://docs.adonisjs.com/guides/session

I've set up `config/session.ts` for cookie storage:

```typescript
import Env from "@ioc:Adonis/Core/Env";
import { sessionConfig } from "@adonisjs/session/build/config";

export default sessionConfig({
  enabled: true,
  driver: Env.get("SESSION_DRIVER"),
  cookieName: "adonis-session",
  clearWithBrowser: false,
  age: "2h",
  cookie: {
    path: "/",
    httpOnly: true,
    sameSite: false,
  },
  file: {},
  redisConnection: "local",
});
```

 and set the following in `.env`:

```
SESSION_DRIVER=cookie
```

I'm trying to use the session in routes, as described in the docs:

```
Route.get("/", async ({ session }) => {
  session.put("test", "hmm");
  return { hello: "world" };
});
```

`session` is highlighted as a problem in VS Code, with the error message "Property `session` does not exist on type `HttpContextContract`" — and requesting the `/` route in my browser shows that `session` is not defined.

Are the docs up to date? Is my `SESSION_DRIVER` correct? How do I access and modify the session?

**Comment by svicalifornia** [comment]
I've added a sample Git repo so you can try to reproduce and tell me what's wrong:

https://github.com/svicalifornia/adonis-session-problem

**Comment by McSneaky** [comment]
https://docs.adonisjs.com/guides/session under "Configure"

`node ace configure @adonisjs/session`

```
# CREATE:  config/session.ts
# UPDATE: .env { "SESSION_DRIVER = cookie" }
# UPDATE: .adonisrc.json { providers += "@adonisjs/session" }
```

**Comment by svicalifornia** [comment]
Ah, I missed those tabs in the code block. Thanks for the assistance.

It would be much easier to follow, IMO, if those would have be separate code blocks instead of tabbed.

**Comment by svicalifornia** [comment]
Slightly off-topic, but it would also be great if the docs section on session config properties specified their precise types. The interface for `SessionConfig` defines `driver` as `any` — presumably because `Env` value are returned as `any` — so it's not super obvious what the allowed values are.

I'd be happy to contribute to the docs if you would like my help.
