### ISSUE TITLE
problem with session age in seconds

### ISSUE THREAD

**Issue by ivan-suhorukov** [adonisjs/session#86]
### Package version

7.4.0

### Describe the bug

Hello! I think i found a bug in file session code. When i sets session age in seconds (e.g. 7200) instead of string (e.g. '2h') i get a wrong session age calculation in this place in session `FileStore`:

![image](https://github.com/adonisjs/session/assets/141321266/9b1c8145-28f3-4c22-8647-0e280a8f3157)

`string.milliseconds.parse()` returns 7200 of milliseconds, then it must be 7200000 milliseconds, so session acts just ~7 seconds.

**Comment by thetutlage** [comment]
Indeed. It should parsed as seconds and then converted to milliseconds for the additional operation.
